[package]
name = 'core-packages/roact-compat'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.1-rc.16.1'
license = 'MIT + Apache 2.0'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'core-packages/luau-polyfill@1.1.0'
React = 'core-packages/react@17.0.1-rc.16'
ReactRoblox = 'core-packages/react-roblox@17.0.1-rc.16'
Shared = 'core-packages/shared@17.0.1-rc.16'
