[package]
name = 'core-packages/string'
description = 'https://github.com/grilme99/CorePackages'
version = '0.0.1'
license = 'MIT + Apache 2.0'
authors = [
    'Roblox',
    'Brooke Rhodes <brooke@gril.me>',
]
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ES7Types = 'core-packages/es-7-types@0.0.1'
Number = 'core-packages/number@0.0.1'
