[package]
name = 'core-packages/react-reconciler'
description = 'https://github.com/grilme99/CorePackages'
version = '17.0.1-rc.16'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
Cryo = 'freddylist/llama@1.1.1'
LuauPolyfill = 'core-packages/luau-polyfill@1.1.0'
Promise = 'evaera/promise@4.0.0'
React = 'core-packages/react@17.0.1-rc.16'
Scheduler = 'core-packages/scheduler@17.0.1-rc.16'
Shared = 'core-packages/shared@17.0.1-rc.16'
