[package]
name = 'core-packages/collections'
description = 'https://github.com/grilme99/CorePackages'
version = '0.0.1'
license = 'MIT + Apache 2.0'
authors = [
    'Roblox',
    'Brooke Rhodes <brooke@gril.me>',
]
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ES7Types = 'core-packages/es7Types@0.0.1'
InstanceOf = 'core-packages/instanceOf@0.0.1'
