[package]
name = 'core-packages/collections'
description = 'https://github.com/grilme99/CorePackages'
version = '1.1.0'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
ES7Types = 'core-packages/es-7-types@1.1.0'
InstanceOf = 'core-packages/instance-of@1.1.0'
