[package]
name = 'core-packages/luau-polyfill'
description = 'https://github.com/grilme99/CorePackages'
version = '0.0.1'
license = 'MIT + Apache 2.0'
authors = [
    'Roblox',
    'Brooke Rhodes <brooke@gril.me>',
]
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
Boolean = 'core-packages/boolean@0.0.1'
Collections = 'core-packages/collections@0.0.1'
Console = 'core-packages/console@0.0.1'
ES7Types = 'core-packages/es-7-types@0.0.1'
InstanceOf = 'core-packages/instance-of@0.0.1'
Math = 'core-packages/math@0.0.1'
Number = 'core-packages/number@0.0.1'
String = 'core-packages/string@0.0.1'
Symbol = 'core-packages/symbol@0.0.1'
Timers = 'core-packages/timers@0.0.1'
