[package]
name = 'core-packages/reactRoblox'
description = 'https://github.com/grilme99/CorePackages'
version = '0.0.1'
license = 'MIT + Apache 2.0'
authors = [
    'Roblox',
    'Brooke Rhodes <brooke@gril.me>',
]
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
LuauPolyfill = 'core-packages/luauPolyfill@0.0.1'
React = 'core-packages/react@0.0.1'
ReactReconciler = 'core-packages/reactReconciler@0.0.1'
Scheduler = 'core-packages/scheduler@0.0.1'
Shared = 'core-packages/shared@0.0.1'
