[package]
name = 'core-packages/luau-polyfill'
description = 'https://github.com/grilme99/CorePackages'
version = '1.1.0'
license = 'MIT'
authors = ['Roblox Corporation']
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
Boolean = 'core-packages/boolean@1.1.0'
Collections = 'core-packages/collections@1.1.0'
Console = 'core-packages/console@1.1.0'
ES7Types = 'core-packages/es-7-types@1.1.0'
InstanceOf = 'core-packages/instance-of@1.1.0'
Math = 'core-packages/math@1.1.0'
Number = 'core-packages/number@1.1.0'
String = 'core-packages/string@1.1.0'
Symbol = 'core-packages/symbol@1.1.0'
Timers = 'core-packages/timers@1.1.0'
