[package]
name = 'core-packages/roactProxy'
description = 'https://github.com/grilme99/CorePackages'
version = '0.0.1'
license = 'MIT + Apache 2.0'
authors = [
    'Roblox',
    'Brooke Rhodes <brooke@gril.me>',
]
registry = 'https://github.com/UpliftGames/wally-index'
realm = 'shared'

[dependencies]
RoactCompat = 'core-packages/roactCompat@0.0.1'
